[package]
name = "mpegts_to_s3"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.0.1"
aws-sdk-s3 = "1.3.0"
aws-types = "1.0.1"
clap = { version = "4.3.3", features = ["derive"] }
pcap = "0.10.0"
tokio = { version = "1.34.0", features = ["full"] }
notify = "5.1.0"
log = "0.4.25"
chrono = "0.4.39"
