version: "3.8"

services:
  ######################################
  # MinIO S3-Compatible Service
  ######################################
  s3minio:
    image: "quay.io/minio/minio:latest"
    network_mode: "host"
    hostname: "s3minio"
    container_name: "s3minio"
    env_file:
      - "config.env"

    volumes:
      - "./data:/data"

    command: >
      server /data
      --console-address ":9001"
      --anonymous --json --quiet
      --certs-dir /root/.minio/certs

    # This ensures the Rust app does not start
    # before MinIO is ready (simple dependency).
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ######################################
  # Rust-Based Capture & HLS Service
  ######################################
  udp-to-hls:
    network_mode: "host"
    hostname: "udp-to-hls"
    # image: docker.io/groovybits/mpegts_to_s3:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DEBUG: "false"
    container_name: "udp-to-hls"
    env_file:
      - "config.env"
    # Mount local 'hls' directory as the working directory
    # where mpegts_to_s3 will write its files.
    volumes:
      - "./hls:/app/hls"
    depends_on:
      - s3minio
    restart: unless-stopped
    entrypoint: ["/app/entrypoint_udp-to-hls.sh"]

  ######################################
  # Rust-Based HLS to UDP Service
  ######################################
  hls-to-udp:
    network_mode: "host"
    hostname: "hls-to-udp"
    # image: docker.io/groovybits/mpegts_to_s3:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DEBUG: "false"
    container_name: "hls-to-udp"
    env_file:
      - "config.env"
    depends_on:
      - s3minio
      - udp-to-hls
    restart: unless-stopped
    entrypoint: ["/app/entrypoint_hls-to-udp.sh"]

  ######################################
  # HLS M3U8 Playlist Service
  ######################################
  hls-http-server:
    image: docker.io/nginx:alpine
    logging:
      driver: none
    container_name: hls-http-server
    ports:
      - "3001:80" # Map port 3001 on the host to port 80 in the container
    volumes:
      - ./hls:/usr/share/nginx/html:ro # Serve HLS files from the local "hls" folder
    restart: unless-stopped
