### BUILD Development Container
FROM almalinux:8.8 as builder

ARG ENABLE_DEBUG
ENV ENABLE_DEBUG=${ENABLE_DEBUG:-false}

ENV PATH="/root/.cargo/bin:${PATH}"
ENV CPUS=16
ENV CARGO_BUILD_JOBS=${CPUS}

## Base probe app in /app directory
WORKDIR /app

# Update system and handle GPG key update
RUN set -eux; \
    rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux && \
    dnf clean all && \
    dnf makecache && \
    dnf update -yq && \
    dnf clean all

# Install dependencies
RUN dnf install -yq almalinux-release-synergy
RUN dnf groupinstall -yq "Development Tools"
RUN dnf install -yq gcc-toolset-13 scl-utils

# Install dependencies for building libltntstools and ffmpeg
RUN dnf install -yq zlib-devel openssl-devel clang clang-devel libpcap-devel nasm \
    libzen-devel librdkafka-devel ncurses-devel libdvbpsi-devel bzip2-devel libcurl-devel;

## Copy Build Files for hls-to-udp and udp-to-hls
COPY Makefile .
COPY Cargo.toml .
COPY src/main.rs src/main.rs
COPY hls-to-udp/src/main.rs hls-to-udp/src/main.rs
COPY hls-to-udp/Cargo.toml hls-to-udp/Cargo.toml

## Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

## Build Rust programs
RUN scl enable gcc-toolset-13 -- make build -j $(nproc) && \
    scl enable gcc-toolset-13 -- make install -j $(nproc) 

###
### END OF BUILD Development Container

###
### START OF Runtime Container
FROM almalinux:8-minimal as binary

## Add the built binaries to the PATH
ENV PATH="/app/bin:${PATH}"

## Set up nvm directory and environment variable
ENV NVM_DIR="/app/.nvm"

## Update system and install dependencies needed for nvm and node
RUN microdnf update -y > /dev/null && \
    microdnf install -y libpcap findutils curl tar gzip

## Install nvm and use it to install Node.js 20, then symlink the node binaries for runtime
RUN mkdir -p ${NVM_DIR} && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash && \
    bash -c "source \$NVM_DIR/nvm.sh && \
    nvm install 20 && \
    nvm alias default 20 && \
    nvm use default && \
    mkdir -p /app/bin && \
    ln -sf \$(nvm which default) /app/bin/node && \
    ln -sf \$(dirname \$(nvm which default))/npm /app/bin/npm && \
    ln -sf \$(dirname \$(nvm which default))/npx /app/bin/npx"

RUN node --version
RUN npm --version

## Copy application binaries and scripts from the builder
COPY --from=builder /app/bin/hls-to-udp /app/bin/hls-to-udp
COPY --from=builder /app/bin/udp-to-hls /app/bin/udp-to-hls

## Quick confirmation that the binaries execute correctly
RUN hls-to-udp -V
RUN udp-to-hls -V

COPY scripts/entrypoint_agent.sh /app/entrypoint_agent.sh

RUN mkdir -p /app/hls
WORKDIR /app

ENV HLS_DIR=""
ENV HOURLY_URLS_LOG="/app/hls/index.txt"
ENV SWAGGER_FILE="/app/swagger_agent.yaml"
COPY recording-playback-server/swagger_agent.yaml ${SWAGGER_FILE}

COPY recording-playback-server/package.json /app/package.json
COPY recording-playback-server/package-lock.json /app/package-lock.json

COPY recording-playback-server/agent.js /app/agent.js

## Install recording-playback-server dependencies
RUN npm install

WORKDIR /app/hls
# Finished building the runtime container
