name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up environment variables
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag groovybits/mpegts_to_s3:${{ env.IMAGE_TAG }}

    - name: Push the Docker image to Docker Hub
      run: docker push groovybits/mpegts_to_s3:${{ env.IMAGE_TAG }}
