name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag groovybits/mpegts_to_s3:$IMAGE_TAG
    - name: Push the Docker image to Docker Hub
      run: |
        IMAGE_TAG=$(date +%s)
        docker push groovybits/mpegts_to_s3:$IMAGE_TAG

